#+OPTIONS: ^:{} _:{} num:t toc:t \n:t
#+SETUPFILE: "../../layout/extension.org"
#+INCLUDE: "../../layout/template-toc.org"
#+title:

* 2015年09月16日
  开盘高开0.4%，次新股率先发力，韩建河山、万林股份、蓝黛传动率先涨停。
  午后沪指开始拉升，盘中一度上涨达5.88%！创业板暴涨7.1%！
  操作失误：5个点时抛掉了韩建河山，2个点时抛掉浪潮软件，这两股均为行业龙头，不该抛。之后高位追了蓝黛传动。
  下午加仓了医药B，尾盘抛部分即将涨停的医药B建仓7个点的新能车B。早就发现新能车B价位不合理，应该早些抛掉部分医药B。

  上海地方股受迪士尼、上海国企改近期是最热门行业，龙头先是锦江投资（两周内近乎翻倍）、界龙实业、龙头股份；现在龙头是大众交通、东方创业、强生控股。

  暴跌后反弹的明显特征是：暴跌两天后，次新股龙头率先发动，大盘在微小区间震荡，此时可大胆抄底分级B赚取20点盈利。
* 2015年09月16日
  继续暴跌。
* 2015年09月14日
  受国企改文件下发影响，早盘高开，之后低走，下午尾盘银行和上证50成分股护盘，最后沪指收跌2.6%，创业板跌7.5%，1500股跌停。
  分级B大部分跌停，只有追踪银行和上证50指数的泛红。
* 2015年09月10日
  早盘低开高走
  受猪肉涨价影响，CPI同比上涨2%，猪肉板块上涨，牧原股份低开高走。
  近下折的分级B在行情好的时候总是受追捧。国防B、新能源B。
  尾盘跳水
* 2015年09月09日
  稍微高开，之后高走，午后稍微跳水，尾盘拉升，收盘2.3。
  午后两桶油极速拉升。石化油服涨停，中石油涨3个点。
  连个8个跌停的科林环保和浪莎股份涨停。本想做T浪莎，7个点抛掉后，没有再捡回。
  新能车B庄非常强势。传媒B封不住。
  上海概念股今天集体打开涨停，行情暂时告一段落。
* 2015年09月08日
  V型。午后银行护盘。
* 2015年09月07日
  大阅兵后第1天，开盘冲高，之后迅速回落。
  军工疲软。
  午后国企改概念迅速回落。原因：国企改文件已下发，国企改概念见光死。
* 2015年09月02日
  低开，中午开始护盘，下午资金疯狂涌出，临近尾盘，银行暴力护盘，工商银行居然涨停。小阳线，但大部分中小股大部分都在跌。
  明天大阅兵。今天和昨天国家队护盘意图明显，虽大盘很漂亮，但中小股全部在跌。中国特色。
  主力今天也判断失误，中午大量主力进场，结果被套。
* 2015年08月31日
  所有人都看多。纳斯达克和标普500均无太大变动。
  沪指低开低走，证券挺累大盘，下午银行有所拉升，尾盘银行暴力拉升，指数回升，但中小板所有股票均下跌。
  两桶油领涨，军工大量出逃资金。
  京运通低开低走，尾盘跌停。盘中抛掉，此次反弹盈利全无。
  重仓军工B，国企改B。
  尾盘暴力拉银行来救指数，表明国家不想在大阅兵前再次出现不稳定因素，明天看好。
  中航动控连3个涨停，俨然军工龙头。
* 2015年08月28日
  暴力反弹。收盘5个点。
  军工指数几乎涨停！
  早盘由于恐惧抛掉了150军工B，没想到军工暴涨。虽然150军工B溢价率非常高（27%），但依旧最后涨停！502军工B溢价更高（42%），居然由跌停到涨停！事实证明市场是非理性的！要想在这种市场中赚钱自己不能太理性。
  抛掉军工B后早上低位入手京运通，理由是前期暴跌近40%，有反弹空间，并且很明显在大单压盘，吸筹意图明显。赚8个点。
  果然渤海租赁反弹无力，虽然有利好，但由于前期跌幅不大，所以涨幅不大，尾盘抛掉，只赚了3个点。
  创业板午后暴力拉升，收盘6.2点！远超沪指。创业板B、成长B涨停，创业B、创业50B由于接近下折，溢价太高，涨幅为5-6%.
  ----------
  此次反弹应该只是小反弹，注意及时止盈。下周三大阅兵休市，周二冲高清仓观望。
  ----------
  {{{lightbox(images/Snip20150828_3.png,800)}}}
  当分级基金母基溢价率比较高且对后期趋势比较看好时，可以买入母基，拆分成AB，溢价套利。比如502军工B，若在25号申购母基金，净值为0.7672；26号申购成功；27号拆分成AB，28号出掉A和B，此时A价格为0.912，B价格为0.724，获利((0.912+0.724)/2-0.7672)/0.7672=6%。
* 2015年08月27日
  正式阶段性反弹开始。高开，两点有大幅跳水，恐惧抛盘严重，之后暴力拉升，收5个点。最后一小时振幅达6个点！
  军工大涨，但150军工B跌停，原因在于溢价率太高，收盘时溢价率为27%。抄底抄在最高点，亏5个点。
  牧原股份持续反弹。
  尾盘高位接盘渤海租赁，10W手涨停压单被逐渐消灭，没禁住诱惑入7手。当时想直到这些单吃完才入，但没有严守纪律。
* 2015年08月26日
  降息降准利好，小幅高开，之后大量资金出逃，大盘快速回落；之后不断冲高，盘中一度冲到4%；尾盘股指期货暴跌挺累大盘，收盘-1.2%。
  当前市场处理恐慌状态，受前两天史无前例连续暴跌影响，股民对后市持悲观态度。
  今日大量开盘或盘中抄底资金被套；上午下午大量割肉割在最低点。
  今天万林、韩建、口子窖再次封涨停。昨天次新异动，抄底万林手慢了几秒抄底失败，改抄雪峰，结果被套，今天做T失败，导致亏损。经验：一定要跟定龙头，其它弱股不要理。
  盘中新通联割肉割在地板上，盘中居然有2个点涨幅，虽然收盘依旧在地板上。耐心不足。
  暴跌之后突发利好，出逃资金巨大，若开盘高开则定要冲高减持，待回落后捡筹码或空仓观望。
* 2015年08月25日
  低开，盘中有少量抄底资金。
  次新龙头暴发（万林股份，韩建河山），口子窖涨停。抄雪峰科技。下午暴跌。倒V
  牧原清仓，亏损3.5K
  至此已亏损1.7W

* 2015年08月24日
  大盘近跌停，盘中两桶油护盘失败
  全球股指暴跌
  全仓跌停
* 2015年08月21日
  大盘低开1个点，中午一度跌到-4.5点，V型反转失败，最后半小时跳水，收盘-4.2。
  军工昨天跌停，今天试图发力，但受大盘拖累。中航动控复牌后可能成为新龙头。
  黄金依旧热，西部黄金，山东黄金成龙头。
  吉电股份中午停牌，引发电改猜测，电改发力。华银电力一度涨停，但最后受大盘拖累遭遇巨大卖单，收盘6.7点。

  今日
  成飞集成上午拉长时没有及时出掉，犯了昨天同样的错误。本可以有1k盈利但由于贪心导致亏损800.
  抛掉成飞集成后入手牧原股份，因为通过前期观察此股一直在57-65区间波动，于是昨天59一手，今天58 57分别一手，结果今天跌停收盘53.81，浮动亏损1.4k。
  入手华银电力6手，吉电股份停牌引电改猜测，所以快速入手华银电力，但午夜吉电公告停牌和电改没关系，估计庄也被深套。浮动盈利400。

  等待周末有无重大利好，有无降准消息。
  满仓被套，下周华银电力及时出，牧原股份不割肉，等待反弹。
  
