#+OPTIONS: ^:{} _:{} num:t toc:t
#+INCLUDE: "./template/log.org"
#+title:

很久没有写日志了。研一算是彻底结束了，这个学期几个月来发生了不少事，令我某些观念发生了很大变化。
---------
退学

虽最终还是没退留了下来，但其中经历了不少风波。

上学期日子实在过得憋屈。因为我有在西交学习Hadoop的经历，便在“大数据”技术的光辉头衔下被负责起了实验室集群的管理工作。开始时我没什么怨言，因为我相信我的导师，“千人计划”的头衔总不能是浪得虚名吧，也许他有他的计划？并且我也很喜欢Linux，有9台超强计算能力的服务器还可以搞点自己的副业：比如在上面做些实验什么的，何乐而不为呢？于是我便开始了我的服务器折腾之路。曾经因为安装OpenStack浪费了几个星期的时间，其实只是官网上几条简单的语句执行一下就可以，但由于服务器的各种奇葩的问题，总是失败。那些语句可以不夸张地说我执行过300遍以上。浪费了大量的时间。

我们是导师的第一届学生，没有任何先前师兄的资料，什么都要自己从新开始弄。并且我完全体会不到研究生导师的指导作用。做的是和科研没什么关系的导师的私活又没有工资补贴。说白了已经完全沦为导师的免费劳力。堂堂上海交大的研究生竟然做起了系统管理员的工作，这可不是我千辛万苦考到这里来的原因。

上课是可有可无的，没有什么有意义的东西。老师在混日子，学生也在混日子。上课就是浪费时间。

直到学期尾的时候，我彻底爆发了。我向导师提出退学，导师没劝直接同意了。我拿着导师签好字的退学申请书找系里老师，问退学流程。给家里打电话说明情况，他们只是让我忍着熬着。我爆发了。父亲联系了系里辅导员，辅导员打电话让我找她，我向来对辅导员没什么好感，想想本科时辅导员的样子就恶心。我拒绝了，差点对她爆发。她也很识趣，毕竟不关她什么事。

当时抑郁到了极点并因此病倒。GJ听说后找到我，劝我，我才知道原来并非只有我一个人这么想，他们都在忍着。他说我做的决定太草率了。SF也来找我，劝我，说我的决定不理智。退了你去做什么？至少拿到文凭，有上交的背景，以后才能混成好日子；你还可以换导师，退学是条绝路，绝路你都敢走还怕直接跟导师翻脸吗？他连劝都不劝直接让你退学，你为什么还顾及他？；导师把学生当苦力是普天皆有的事，你以为清华北大不是这样吗？；……我被说动了。虽然我现在才明白并非每个人都是出自真心帮我，但无所谓了。想到自己考研时受的苦，不能白受，半年时间不能白白浪费。于是当系里老师打电话再次问我的时候，我说：我后悔了，我不退了。这是我到那时为止做过的最厚脸皮的一件事。

之后的事就很简单的了，厚着脸皮找新导师，找原导师签字转导师。这次退学风波就这么平息了下来。只留下两门没考的课程做为这件事曾经发生过的见证。
---------
项目

我向来喜欢自由，所以选择新导师的时候找的是SF舍友的导师，他也确实没有骗我，但当我进去之后仿佛世界变了。本以为会有大量时间做自己喜欢做的东西时，导师开始大手笔的接外包项目。

计算机系的学生不会编程怎么能行？成为每次说道的金句。

导师在徐汇而我在闵行，每次不得不花至少3个小时的时间来回折腾。

关于费用自然你懂的。我目前正在为一个基金公司做内部管理系统，负责人是导师之前的学生，估计也是一时脑子发热本以为找学生做能省下一笔不小的费用，结果却翻了船。不过好在花的是公司的钱，她似乎也不怎么在乎。

我还是能从这个项目中学到东西的，因为有经验丰富的高手在指导。但研二那些人就不像我这么幸运了。他们需要在很短的时间内在没什么经验的情况下开发手机APP。一群壮志雄心但走了弯路的创业家，虽然有手机APP很重要，但这根本不是核心。不应该把它交给一群没有经验的孩子来做。应该去找外包公司，宁可多花些钱。这也给我一个警示：如果将来我创业绝对不会将这种项目交给学校来做，即使便宜。
---------
炒股

研二师兄的某位老师曾经对他选择西安交大还是上海交大提出的建议是：如果你想学到真知识，建议去西安交大。我现在对这句话有些领悟。上海是个非常浮躁的城市，完全没有西安那种深沉深厚历史气息的氛围。在上海完全静不下心来做研究。

上海的消费水平之高让我对金钱有了非常高的渴望，另外周围有一批人包括导师在内，每次开会都要谈论半天的股市，我也自然而然耳濡目染。开始的时候我看得非常清楚，股市就是赌场，即使再好的技术分析在当前这种乱世也不起作用，所以炒股就是赌博。后来我入市了，虽然我知道我在赌博，但它给人带来的快感另人欲罢不能，即使是亏钱。股市永远让人满怀期望，即使当天跌得一塌糊涂，你也能给自己找到充足的明天上涨的理由。即使你明知道这只股很有可能继续跌下去，但你还是不想割肉，因为割肉就表明亏钱已成事实，而套在里面就永远有可能回本的期待。别人永远只会给你讲他们怎么赚钱，自己怎么牛逼抓住时机建仓，抓住时机做T，他们只是在寻找存在感。股市亏多赚少，跌起来容易涨起来难。从50涨到100要涨100%，但从100跌到50只需要跌50%。亏钱很容易，赚钱真的很难。

未入市前宝哥经常跟我讲自己一天赚1W，怎么怎么牛逼，然而事实是大势好，随便买都可以赚到钱，本金多则赚得多。但当熊市来的时候（至少从技术面上分析现在已经处于熊市当中），任你技术再好，2000+跌停怎么做T？一天亏1W2W是很正常的。

通过这段时间炒股我至少明白了另外一种赚钱的渠道，世上不是只有实业可以赚钱，资本也可以，并且资本赚钱比实业赚钱来得更快更多，前提是你有那个本事。

技术不是唯一的，技术只是赚钱谋生的一种手段。即使你真热爱技术，也不要一辈子只埋头技术。当把一件事当做兴趣来做的时候你才有可能坚持一辈子，而一旦它成为你谋生的手段，不得不做时，你早晚会对它产生厌倦。所以学些其它生财之道，将你热爱的技术当作副业，这样才能长久。

我能明白这些，我这一个月来亏的4K+就算不白亏。
---------
情感

孤独很久了。

我总以为我可以一直这样下去，一个人安安静静地过自己想过的人生。但有一天我突然想到，我是不是该找个爱人？大三下学期我就一个人在外租房，共在外住了两年半，前前后后换过6个房东，经过一天工作学习后拖着疲惫的身体回到家，面对空空荡荡的房间，那种孤独的感觉我深有体会。直到有一天我突然想起这种感受来，我觉得我需要做些什么了。

于是我很不要脸地联系了YX，我想不到去联系谁，也没有谁值得我去联系。我只是想聊聊天，想说说话，虽然我也不知道该说些什么。

YX性格上有个很大的优点就是很会给人台阶下，其实这也是个缺点，因为她总是给我很不明确的表态，再加上我从小一根筋根本不知道该如何解读。这和我想象中不一样。

回忆里的人也许真的不能见。时间会冲淡一切，但会留下你想留下的。根据这些刻意挑拣的过时的回忆已经不足以对当下的情况做出准确地判断了。她这些年经历了什么，我完全不了解，我无法根据旧的回忆判断她当前的自己。

所以我想了解，但根本没有机会。
---------
沟通

最近在看一本书《沟通的艺术》。发现我以前根本不会与人沟通，我总是想别人会明白我的意思，但事实上由于各种各样的原因，比如性别经验文化生理心情等，他们根本不明白。而我有话从来不说第二遍。各种各样的冲突矛盾就这样产生了。

我在想如果当初我时常与YX沟通而不是几周几周地不说话，事情会不会不是现在这样……

至少我现在明白了。
