#+OPTIONS: ^:{} _:{} num:t toc:t
#+INCLUDE: "./template/log.org"
#+title:
2014年10月25日21:08

开学至今40多天了，研究生的生活并不如意。

首先要承认的是在中国读研并不是明智的选择，虽然我并没亲身体会外国研究生的生活。或许读研本身就不是明智的选择，谁知道呢？我现在的生活完全在重蹈在西交工作的覆辙，我很清楚这样下去的结果是什么：先把自己的耐性磨完再撂挑子。这不是我想要的生活，但我没有办法。我们3个是我导师的第一届研究生，没有师兄，没有任何可以参考的研究资料；我所在的实验室尚未成形，和在西交工作的实验室一样，服务器整日嗡嗡响不停；由于供出在自己在西交学过Hadoop的经历，便被要求负责服务器；导师眼里我们就是廉价劳动力，从来不提科研，只是让我们几个给他的公司干活，没有人指导，完全自己瞎琢磨，浪费时间……

我总是说这不是我想要的生活，但我想要什么样的生活，我也说不清楚。

另外要承认的是考研保研是人群再重组的过程，它将某些兴趣相同的人聚在一起。比如高中大学时，我总是显得很另类，在某些人眼里我很自负，以自我为中心，其实后来我发现对计算机感兴趣的或多或少都有这些毛病，而现在我周围的一些人证实了我的观点。前几天的某些瞬间我感觉自己突然跳出了自我封闭的空间，以旁观者的角度来客观的观察自己：我并非我想象中的完美，我的所有形象不过是建立在辛苦的掩饰下。我懒惰、任性、拖延、自负，当出现了问题，我总是逃避或推脱责任来维护自己完美形象，而事实上我的这种做法往往导致事情越来越糟糕。

资金方面出现了大缺口，由于上次一气之下将手机弄坏，不得不花2k+买台新的，导致生活越来越拮据。再加上上海消费实在高，导致现在花钱总是畏手畏脚，除了正常吃饭花钱外其它什么都不敢买。

我对大城市的孩子总是很有偏见，先是本科北京舍友，现在是上海舍友：仿佛生活都不能自理。之前北京舍友总是把宿舍搞得臭气熏天，现在上海舍友每周带脏衣服回家。或许这种做法在他看来没什么不妥，但你已经不是小孩了。

今晚第一次去健身房，没有想象中好。先是断断续续在跑步机上跑了30分钟，之后到器材室时就不知所措了，完全不知道各个器材怎么用，并且器材室很小，感觉人挤人完全活动不开。并且跑步机上跑步完全没有操场上痛快。所以决定交替跑步和健身，跑步时去操场，健身时去健身房。任何时候身体最重要。
