#+OPTIONS: ^:{} _:{} num:t toc:t
#+INCLUDE: "./template/log.org"
#+title:

2014年07月22日06:24

距离上次写日志已经很久了。

天越来越热，人也越来越躁动不安。仍旧在西安交大理学院一个实验室做临时工性质的工作，5月底的时候回家了一次，请假的理由是颈椎病复发，需要休息。事实也确实如此。我对自己的定位是“完美主义者”，当我做某件事的时候，要么不做，要做就要做得最好。所以开始学习技术的时候，全身心的投入，忽视了自己的健康状况，以致后来颈椎病复发。

不过我有所隐瞒。除身体原因外，还有一个原因是我开始对现状感到厌倦。

1. 之前曾经就说过，我对实验室环境非常不喜欢，依我看来，那根本不能称作实验室，根本不适合在里面搞研究。
2. 老师只是将我当成随意使唤的工具，我并不感受到应有的尊重。比如让我跑腿办一件他之前已经办过，明知办不成的事，酷热天气下我用了两个小时来回跑了4次，像一只可怜虫向我不认识的人摇尾乞怜；比如某博士给我一份有错的文档让我编程，直到我浪费了至少两个星期时间调试未果后才指出来。我在这两个月里浪费了大量的时间。
3. 之前曾经说过，我所在实验室里只有我一个人在搞Hadoop，老师根本不懂，对我的指导几乎为零并时不时对我进行错误的指导。这里没有学技术的氛围，其它人对技术并不感兴趣，所有问题全部自己解决。以前我偏执地认为学技术就是要独自解决问题，因为只有自己亲自解决的才能有收获。但经过这两个月的经历，我的观点有所改变：{{{color(red,学技术必须要站在前人的肩膀上)}}}。因为这样可以省去许多不必浪费的时间，但这并不意味着就可以放松对自己的要求，要想真正精通还是要花许多时间和精力，有些问题还是要自己独立解决。所以我现在有些后悔考研结束后留在西交，我应该去上交找导师，去那边的实验室，因为那里的牛人更多，我会有更大的提高。

那次跑腿经历也并非一无所获，我知道那次报账肯定有问题，具体我说不清楚。从这件事我看到中国科研经费管理方面有问题，也看到有些本来令人尊敬的人是不值得令人尊敬的。

这些天晚上总是失眠，主要是因为天太热。搬新家的时候本没有将空调考虑在内是我的疏忽。经过搬几次家的经历，我发现我是个非常容易被骗的社会小白：上次在学府首座租单间考研，房租750，我走后立刻700租给别人；这次在交大一村租的单间也是750，但我无意中看到我之前租客的房租是700.两次租房我都没有砍价，基本上他们说房租是多少我就拿多少。就当是教训吧。

可以说，除了工资束缚之外，我已经没有理由继续留在西安了。虽在这个城市生活了五年之久，但我对它并无多少留恋，城市化本来就是如此。只盼这个炎热的夏季早些过去。

#+INCLUDE: "../../layout/disqus.org"
