#+OPTIONS: ^:{} _:{} num:t toc:t
#+SETUPFILE: "../../layout/extension.org"
#+INCLUDE: "./template/log.org"
#+title:

{{{lightbox(images/东方明珠塔.jpg,300)}}} 
2014年03月30日22:40

考研结束了，虽然正式结果还没出来，不过想到自己复试的表现加上实验室负责人的电话确认，我对自己已经被录取的事实非常确信。

原本想过如果被录取了一定要写篇长文记录下自己这8个月的所作所为及成功的经验以供各位看官娱乐消遣或为后来考研者提供些经验借鉴，但迟迟没有下笔，因为完全事后诸葛写出一篇完全意淫出来的文章，肯定是我不想的，但如果完全如实记录地话，有一些日子颓废堕落简直不堪回首，所以作罢。至于对于后来考研者提供帮助，只能对你们自己去[[http://cskaoyan.com][王道论坛]]上搜索吧，当然我说的是方向是计算机。

想想这两个星期的所为还是有些后怕，因为很有可能我在这两个星期里做出了决定我一生职业方向的选择。说来世事真是巧得很，当初做毕设向是GPU并行计算，到了上交复试让确认研究方向的时候，我只知道并行编程，于是就决定选这方面。当初统考刚结束，做毕设时的导师想让我去他实验室帮忙，每月3k（国家的钱，但做的是他的私活），关于大数据Hadoop方面的，巧的是上交EPICC实验室负责人跟我联系问我愿不愿意加入他们的实验室方向也是云计算大数据处理方面，我就这方面也很感兴趣，于是便答应了。昨天那位负责人给我打电话想让我早些过去熟悉环境（说白了是想利用我这个廉价劳力而已），我跟他说了我现在在西交的一个实验室学Hadoop方面的，他说他那边也是在做Hadoop方面的。这一切简直太巧了。

从上海回来后搬了一次家，在校内里租了一个单间，环境不是很好不过在容忍度之内，重要的是离自习室和食堂很近，每天要节省不少时间。暂时没有网络，不过正合我意，因为我发现我在有wifi的环境下大多数时间都花了手机和电脑上，虽然有收获，但总觉得没有读书收获有意义，我在我的Kindle里存了很多书，没有网络，我每天可以有更多的时间阅读。

现在每周正常上班似的要去毕设老师的实验室，不能像上学那会儿随便逃掉，因为我现在拿着工资。我对那个实验室并没有什么好感，一个很小的实验室要挤8个人，经常被打扰，并且由于使用人多的缘故实验室的网速很慢（这似乎是西交所有实验室的通病）。实验室里学Hadoop的也就我一个人，我估计老师也不是很懂，他只是看中了我在跟他做毕设时的快速自学CUDA的能力，于是他相信我也能快速地学会Hadoop，但事实上Hadoop要难得多，尤其是从前完全没有接触过，而且要用Hadoop做项目必须对Java相当熟悉，虽然我之前自学过Java但当时完全一知半解。虽然有困难，但我已经决定把它学会，反正早晚都要学，到了上交那边也是搞这方面的。

我现在对读书有了新的认识，自从买了Kindle之后发现自己慢慢喜欢上了读书，我在我的Kindle里存了许多书，各个方面的都有:经济政治历史技术小说自传，每次我都会看自己的心情找一本合适的书来读，每次都或多或少的有所收获。上学的时候曾看到过许多这样那样的文章说年轻人应该多读书，杨绛的名言：你的主要问题在于书读太少而想得太多。当时不是很明白，其实只有当自己开始阅读的时候才会领悟。现在非常悔恨大学时候浪费了许多美好时光在无用事物上。

不过一切都过去了，大学时好的不好的回忆，快乐或不快乐的时光，经历过大学固有的或偶然的磨炼后，现在是个完全新的开始，我发现自己有太多的书要读，有太多的技术要学，我要充实过好之后的每一天。
