#+OPTIONS: ^:{} _:{} num:t toc:t
#+INCLUDE: "./template/log.org"
#+title:
2014年04月06日19:13

清明前一天(4/4)上交录取结果出来了，一切都在意料之中，如愿被录取。

工作上仍在学hadoop，目前完全处于初级阶段，目前遇到的主要障碍是Java，现在才发现以前自己的Java水平根本不能叫一知半解，而是根本不懂。老师按照他的要求每天给我布置任务，不过他好像不是很清楚我的底细，不过也好，我可以有更多的时候来提前学习自认为之后要用到的更有用的东西，只是这种每天让人督促的方式让我很不爽，我想我应该习惯，因为之后不管是读研还是工作都不可能像大学时候那样自由了。

这一周校园里多了好多来赏樱花的人，西交的樱花确实漂亮，看见多个背着沉重相机扛着机架前来赏花的人，我总是很不理解这些人到底知不知道自己是来干嘛的。

阅读方面，这一周每天都要用2个小时左右的时间来读《平凡的世界》，现在已经读了近一半了，我很喜欢这类描写农村现实的文学作品，和之前读过的《白鹿原》《活着》很类似。可能是我出生在农村的缘故，我每次读这些书总能将其中的人物与我认识的某个叔伯或认识的庄稼人相联系起来，好像他描述的这个人就在我身边一样。但我清楚，不管是在哪个年代，农民阶级注定都是最下等的阶级，封建时代如此，新中国成立后也是如此，毛泽东的高明之处在于他可以将农民这个阶级玩弄于股掌之间，他明白农民身上固有的劣根性，他知道农民需要什么，他知道怎么教育农民才能为自己所用。我发现自己现在的状态现在就是年轻时代的孙少平，出生在农村但在大城市里受过些教育，我不可能成为地道的农民也不可能成为地道的城市居民，身上兼具二者气质，永远游离于二者之间。

《拖延心理学》是网上流传的香港大学推荐的50本经典书籍之一，读到拖延怪圈的时候便被深深吸引住了，结合自己两次考研的经历，发现这本书简直为我量身定制。书中写道拖延怪圈一般有7步：
#+BEGIN_EXAMPLE
1.这次我想早点开始。
2.我得马上开始。
3.我不开始又怎么样呢？
  a. 责备自己应该早些开始
  b. 做其它事情的愿望特别强烈
  c. 分散注意力以逃避压力
  d. 欺骗
4.还有时间。
5.我这个有毛病。
6.最后的抉择：做还是不做。
7.我永远不会再拖延。
#+END_EXAMPLE
第一次准备考研是在大三，我想早点开始准备，于是在4月的时候在外租房搬出宿舍，想着时间还早，于是整天混混度日；直到七月，发现和其它考研者相比自己时间上已经没有优势了，于是我想我必须要马上开始了，但我又想此时距考研日期还早呢，我还是很有机会的；时间又过去了，我还是没有准备，于是我开始责备自己当初早些准备就好了，与此同时我发现自己学Lisp的愿望特别强烈，于是花了大量时间学习Lisp，几乎每天都在愧疚中度过，10月左右我还花了600块钱报了政治辅导班，经常跑到很远的地方上课，在外人看来一幅勤奋刻苦的样子；虽然明显感觉时间流逝，但我依旧在想我还有时间；直到12月多，我发现以我现在的水平根本不可能考上，同时我再也忍受不了这种折磨了，于是我放弃了，第一次考研以放弃而告终。

之后开始做毕设，直到第二年7月再次开始准备考研，开始信心满满，也很努力，到后面很疲惫，每周只有两三天时间在学而已，几个月没有上过网，后来上网的欲望特别强烈，因为出租屋里没网，于是经常去网吧熬通宵然后白天回来睡觉，这样日子持续了一段时间之后，离考研日子已经不多了，于是我发誓日子不能再这样下去了，我要孤注一掷，现在的我目标已经不再是考400+，而是能够过线就好，考完后我一直以为自己肯定不会过线，但上天还是比较眷顾我，358，勉勉强强地过了线。最后复试逆袭，被录取。

书中在前言中就写道要想彻底摆脱拖延的习惯必须结合自身的经历从中总结出经验，这样才能理解的深刻，才能避免重蹈覆辙，将之前说过不想再提的考研经历写出来也算是一种正视自我的一种方式，我确实在这整整两年里两次考研的经历过程中学到了终身受用的经验。

除此之外还读了《黑客与画家》的第一章“为什么书呆子不受欢迎”。书呆子受人排斥的主要原因不是别人多讨厌书呆子，而是那些受欢迎的人巩固自己的亲密关系的手段，就像一个政客把人民团结在自己周围最好的办法就是向它国宣战，一个国家想团结另一个国家的最好手段就是结成联盟向它国宣战，这让我想起18届大会权力交接时的钓鱼岛事件，这个事件到底谁是幕后策划人？我现在有些怀疑。
