#+OPTIONS: ^:{} _:{} num:t toc:t \n:t
#+SETUPFILE: "../../layout/extension.org"
#+INCLUDE: "../../layout/template-toc.org"
#+title:

* 股指期货
  http://finance.sina.com.cn/futuremarket/yspzs/20060706/13512710777.shtml
  　　以某一股票市场的股票指数为例，假定当前股票大盘指数是1000点，也就是说，这个市场指数目前现货的“价格”是1000点，现在有一个“12月底到期的指数期货合约”，如果市场上大多数投资者看涨，可能同一时刻这个指数的期货价格已经达到1100点了。假如你认为将来这一指数的“价格”会超过1100点，你就可以买入这一股指期货。过后，这一指数期货继续上涨到一定价格，假设是1150点，这时，你有两个选择，或者是继续持有你的期货合约，或者是以当前新的“价格”，也就是1150点卖出这一期货，这时，你就完成平仓，从而获得了50点的差价收益。当然，在这一指数期货到期前，其“价格”也有可能下跌，你同样可以继续持有或者{{{color(red,平仓割肉)}}} 。反过来，假设你认为将来股票大盘指数要跌，这时你可以在股指期货上先卖出股指期货合约作为开仓，过后，股指期货价格跌到1050点，你就可以选择平仓，即，买入相应的“股指期货合约”用来抵消掉先前的开仓合约，这样你就赚得差价50点。
  　　这种买卖就是股指期货交易。
  
  　　但是，当股指期货到期时，这时谁都不能继续持有了，因为这时的期货已经变成“现货”，你就必须履行交割。
  　　股指期货的交割：就是根据你持有的期货合约的“价格”与当前现货市场的实际“价格”之间的价差，进行多退少补，相当于以交割那天的现货 “价格”平仓。上例中，假如12月底到期时，你仍然持有的买进合约就需要交割，合约价位点数是1100点，这时，股票现货市场指数的结算价点位是1130点，你就可以得到30个点的差价补偿，也就是说你赚了30个点。相反，假如到时指数的结算价点位是1050点的话，低于你的买价50个点，你就必须拿出50个点来补贴，也就是说亏损了50个点。
  
  　　当然，所谓赚或亏的“点数”是没有意义的，必须把这些点折算成有意义的货币单位。具体折算成多少，在股指期货合约中是事先约定好的，称为{{{color(red,合约乘数)}}}。假如规定股指期货的合约乘数是100元，也即每个点值100元，那么赢利30点就是赢利3000元。
  
  　　假设股指期货的点位是1000点，一个合约的价值就是100000元。目前，香港恒生指数大概在15600点左右，合约乘数是50港币，这样，一份香港恒指期货合约价值大概在780000港币。
* 利用股指期货套期保值
  http://zhidao.baidu.com/link?url=ZUQx-IISomcjrlaVgPnmD60EyHl-Kq169GV7u_La3SR6vYQUhPghrYQ7URF1mO_b0cH-PdrP7SgRCP65c-exGK
  空头套期保值（卖出套保）空头套期保值是指通过卖出股票指数期货合约从而达到保值目的。这是针对股市看跌的一种保值措施，它是通过期货合约的收益弥补股市下跌而造成持有股票的损失，它是为现货市场中正持有的股票进行保值的一种手段。
  
  例：某投资者持有某公司股票10000股，每股价格为20元，此时股市指数为2000点。该投资者认为，在未来2个月股票市场行情看跌，股指期货也会下跌，投资者所持有的股票也会随之下跌，但他又不愿意卖出手中的股票（或者是由于交易清淡卖不出去）。为了规避这种可能的损失，该投资者便在股指期货的2000点卖出2手股指期货合约（{{{color(red,每手保证金)}}} 仍为10000元，每点值100元）。两个月后，股市大盘指数跌至1800点，期货指数也跌至1800点，投资者所持有的股票已跌至每股16元。该投资者在股票现货市场的利润缩水了，而同期股指期货也跌至1800点，该投资者便买进两手股指期货合约平仓。这样，该投资者在期货合约上的盈利正好可以弥补同期在股票现货市场上的损失。
  该投资者的整个操作过程计算如下（为计算方便，仍不计算各项税费）
  A、下跌前的操作（股票大盘2000点，股票价格每股20元，期指价格2000点，每点值100元）
  此时股票市值：10000股×20元／股＝200000元
  卖出2手股指期货合约（开仓）成本：10000元／手×2手＝20000元
  B、下跌后的操作
  此时股票市值10000股×16元／股＝160000元
  下跌前股票市值200000元－下跌后股票市值160000元＝40000元，即投资者在股票现货上损失40000元。
  买进2手股票期货合约（平仓）盈利：（2000点－1800点）×100元／点×2手＝40000元。
  这样该投资者虽然在股票现货市场上损失了40000元，但在股指期货市场的交易中得到了全部弥补，锁定了利润，达到了保值的目的。
  股票指数期货的套期保值功能是很实用的，即使投资者对股市大盘很不了解，做多做空无从选择，但仅从保值的目的讲，无论是在指数期货上做多还是做空，都可以弥补股市波动给投资者带来的系统性风险。当股市走势与投资者所预料的趋势相反时，投资者在期货市场上会遭受损失，但在股票现货市场又可以获利。这样可以达到保值的目的。当然，实践中投资者不可能做到前述示例中那样绝对分毫不差的完全保值，但只要依照上述思路操作，即使有损失，也是很少的，同样会达到大幅度地减小风险的目的。
* 空头/多头/空头平仓/多头平仓
  * 开仓指的是建立新的期货合约.
  * 平仓指的是平掉原来已有的头寸.
  * 空头指虽然当前股价相对较高，但是投资者对股市前景不看好，预计股价将会下跌，于是趁相对高价时卖出股票，待股票下降至某一价位时再买入，以获取差额收益。
  * 多头指投资者对股市看好，预计股价将会看涨，于是趁低价时买进股票，待股票上涨至某一价位时再卖出，以获取差额收益。
  * 多头开仓, 指建立一个买进的新合约.
  * 多头平仓, 指平掉原有的买进的合约.(即卖)
  * 空头开仓, 指建立一个卖出的新合约.
  * 空头平仓, 指平掉原有的卖出的合约.（即买）
  * 做多就是做多头。
  * 做空就是做空头。
* 期权与权证的区别
  http://stock.hexun.com/2014-03-17/163084203.html
  期权与权证都是一种选择权。在支付一定的权利金后，给予持有者按照合约内容，在规定的期间内或特定的到期日，按约定价格买入或卖出标的资产的权利。是持有者一种权利（但没有义务）的证明。但两者又存在许多的差别：
  1. 发行主体不同。期权没有发行人，每一位市场参与人在有足够保证金的前提下都可以是期权的卖方。期权交易是不同投资者之间的交易。当投资者买入某公司的认购期权时，卖出期权的是普通投资者。而权证通常是由标的证券上市公司、投资银行（证券公司）或大股东等第三方发行的。交易双方为股票权证的发行人与持有人。当投资者买入A公司的权证时，卖出权证的是A公司自己或者它所委托的证券公司。如果卖出的机构是A公司自己，则称为股本权证；卖出的机构是证券公司，则称为备兑权证。
  2. 交易方式不同，期权交易比权证更灵活。投资者可以买入或卖出认购期权，也可以买入或者卖出认沽期权。但对于权证，普通投资者只能买入权证，只有发行人才可以卖出权证收取权利金。当然投资者也可以在二级市场交易手中已有的权证。
  3. 合约特点不同，期权合约是标准化合约而权证不是。期权合约中的行权价格、标的物和到期时间等都是由市场统一规定好的，而权证合约中的行权价格、标的物、到期时间等都是由发行者决定的。
  4. 合约供给量不同。期权在理论上供给无限，不断交易就不断产生。而权证的供给有限，由发行人确定，受发行人的意愿、资金能力以及市场上流通的标的证券数量等因素限制。
  5. 履约担保不同。期权的开仓一方因承担义务需要缴纳保证金，其随标的证券市值变动而变动。而权证的发行人以其资产或信用担保履行。
  6. 行权后效果不同。认购期权或认沽期权的行权，仅是标的证券在不同投资者之间的相互转移，不影响上市公司的实际流通总股本数；对于上市公司发行的股本权证，当投资者对持有的认购权证行权时，发行人必须按照约定的股份数增发新的股票，从而导致公司的实际流通总股本数增加。
* 锁仓
  http://baike.baidu.com/view/509741.htm
  黄金当前为100元，交易者认为会涨（根据技术研究判断趋势），入场做多，买入。黄金突然下跌，变成95元，并且市场信息表明价格形态趋势有可能反转，交易者犹豫，开始怀疑自己的判断，这时他实际亏损5元。
  交易者进行对锁操作，在95元做空增加一单卖出。这样，交易者有两手单子，一个是100买入，一个是95卖出，中间亏损5元被锁定。不管市场如何波动，交易者的亏损被锁定在5元。而过了市场犹豫期后，黄金中期进入下降通道，而交易者也经过技术研究确认趋势反转，假定这时价格下跌为90元，交易者决定解锁，结算多单（亏损头寸优先解锁），这时亏损仍然是5元（空单有利润）。
* ST股票
  ST是英文Special Treatment 缩写，意即"特别处理"。该政策自1998年4月22日起实行，针对的对象是出现财务状况或其他状况异常的上市公司。
  所谓"财务状况异常"是指以下几种情况：
  1. 最近两个会计年度的审计结果显示的净利润为负值，也就是说，如果一家 {{{color(red,上市公司连续两年亏损或每股净资产低于股票面值)}}} ，就要予以特别处理。
  2. 最近一个会计年度的审计结果显示其股东权益低于注册资本。也就是说，如果一家上市公司连续两年亏损或每股净资产低于股票面值，就要予以特别处理。
  3. 注册会计师对最近一个会计年度的财产报告出具无法表示意见或否定意见的审计报告。
  4. 最近一个会计年度经审计的股东权益扣除注册会计师、有关部门不予确认的部分 ，低于注册资本。
  5. 最近一份经审计的财务报告对上年度利润进行调整，导致连续两个会计年度亏损。
  6. 经交易所或中国证监会认定为财务状况异常的。
　{{{color(red,ST股票日涨跌幅限制为5%)}}} ，需要指出的是，特别处理并不是对上市公司的处罚，而只是对上市公司目前所处状况的一种客观揭示，其目的在于向投资者提示市场风险，引导投资者进行理性投资，如果公司异常状况消除，可以恢复正常交易。
  *ST是指连续3年亏损有退市风险而被特别处理的。
* 斩仓/割肉/停损
  当投资者的账户净值除以占用的保证金低于规定水平时，投资者没有及时补交保证金的情况下，公司将不得不采取强行平仓的举动 or 投资者为防止亏损扩大而采取的止损行为都称为斩仓。比如在买入币品（或股票或期货）后，①币价（或股票或期货）下跌，投资者为避免损失扩大而低价卖出币品（或股票）；②为需资金周转而低价卖出币品（或股票）。这种投资行为叫做斩仓，又称割肉、停损。
* 仓位
  http://baike.baidu.com/view/495146.htm
  仓位是指投资人实有投资和实际投资资金的比例。列举个例子：比如你有10万用于投资基金，现用了4万元买基金或股票，你的仓位是40%。如你全买了基金或股票，你就满仓了。如你全部赎回基金卖出股票，你就空仓了。
* 老鼠仓
  http://baike.baidu.com/link?url=8B8n1TYeMFToqAvSMXMrNFBfjYwmxPUTNOD7w0NSDI6h8elAljr-SDsIIWiFezp4jGugjlOsKRw1p5ggPflyMt2wDRBiVMEErHj4-cSGDt7
  老鼠仓是指庄家在用公有资金在拉升股价之前，先用自己个人（机构负责人，操盘手及其亲属，关系户）的资金在低位建仓，待用公有资金拉升到高位后个人仓位率先卖出获利，当然，最后亏损的是公家资金。
